site_name: bakelite
site_description: bakelite project description
site_author: Emma Powers

repo_url: https://github.com/emmapowers/bakelite
edit_uri: https://github.com/emmapowers/bakelite/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
